### ISSUE TITLE
"Cations" command does not load

### ISSUE THREAD

**Issue by PacRepos** [Alcryst/cations#3]
Completed most installation instructions, however upon attempting to activate program using the cations command it claims that the command does not exist.

`zsh: command not found: cations`

Reloaded and cd'd into the directory multiple times with no success.

Even after developer support this command still fails to work.

**Comment by Alcryst** [comment]
Your Python installation should have modified your $PATH variable such that you can run Python scripts in your system's scripts folder.

Updating your Python version with an official installer would be best if feasible. You could otherwise consider manually editing your $PATH variable. Since you're using zsh (thus assuming you're using MacOS), navigate to the .zshrc file (or create it if one doesn't exist), type pip3 list -v, copy the file path shown up to ".../Versions/3.XX/lib" (replace lib with bin), and paste into your .zshrc file: `PATH=[your copied path]:$PATH` like so. Make sure you've replaced lib with bin. More information on how to edit your .zshrc file can be found [here](https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path).

Hope all else goes well for you!

**Comment by PacRepos** [comment]
Ballz lmao heheheha
![download](https://github.com/user-attachments/assets/a5e20331-c2bf-4429-83b3-859dae0f4c1f)

**Comment by PacRepos** [comment]
![download](https://github.com/user-attachments/assets/4c44cc62-99d6-4ca6-a11a-084011d71d13)
