### ISSUE TITLE
Multiples errors on startup

### ISSUE THREAD

**Issue by Zachmd14** [Alcryst/cations#4]
I installed the app as specified in the README, but got this error when typing `cation` :

```
❯ cations
Traceback (most recent call last):
  File "/home/zach/Apps/sublime-reddit/myenv/bin/cations", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zach/Apps/cations/cations_dir/__main__.py", line 374, in main
    configStr = loadConfig()
                ^^^^^^^^^^^^
  File "/home/zach/Apps/cations/cations_dir/__main__.py", line 29, in loadConfig
    f = open(str(os.path.expanduser('~')) + "/cations/cations_dir/user_data/config.txt", "r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/zach/cations/cations_dir/user_data/config.txt'
```

**Comment by Alcryst** [comment]
My guess as to what happened is that the repository was cloned into a directory that wasn't the home directory, and the (previous version of the) program erroneously assumed the file would always be running from the home directory. I've fixed all file accessing methods now so that they reference the actual location of the directory no matter where it is.

You could uninstall and reinstall the whole application or simply just replace the "__main__.py" file at (wherever the repository is)/cations/cations_dir/__main__.py with the fixed version. I'll add instructions to fully uninstall cations to the README in case you want to do the first option.

Hope this helps fix the issue! Thank you so much for using cations, and please reach out if you have any other concerns or suggestions!! :)
